language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - npm install

before_install:
  - travis_retry composer self-update

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.example .env
  - php artisan key:generate
  - php artisan serve &

script:
  - php artisan dusk